// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1rmK3T-ki3VrxqDlivQV8f98LazXnxg',
    appId: '1:253163256490:web:65d204e72e410a200feed3',
    messagingSenderId: '253163256490',
    projectId: 'daily-expense-tracker-b8415',
    authDomain: 'daily-expense-tracker-b8415.firebaseapp.com',
    storageBucket: 'daily-expense-tracker-b8415.firebasestorage.app',
    measurementId: 'G-H7ZH59TQ4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmofFzWfeImIFMIXQXsdJprCKX08UVO6g',
    appId: '1:253163256490:android:e8f26a09484c6da70feed3',
    messagingSenderId: '253163256490',
    projectId: 'daily-expense-tracker-b8415',
    storageBucket: 'daily-expense-tracker-b8415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_2HKBgAI0cikFmfKN41YA3CuFHdW15kk',
    appId: '1:253163256490:ios:63e44337a4616c600feed3',
    messagingSenderId: '253163256490',
    projectId: 'daily-expense-tracker-b8415',
    storageBucket: 'daily-expense-tracker-b8415.firebasestorage.app',
    iosBundleId: 'com.example.dailyExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_2HKBgAI0cikFmfKN41YA3CuFHdW15kk',
    appId: '1:253163256490:ios:63e44337a4616c600feed3',
    messagingSenderId: '253163256490',
    projectId: 'daily-expense-tracker-b8415',
    storageBucket: 'daily-expense-tracker-b8415.firebasestorage.app',
    iosBundleId: 'com.example.dailyExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw1rmK3T-ki3VrxqDlivQV8f98LazXnxg',
    appId: '1:253163256490:web:bfa0e3e6698b5c540feed3',
    messagingSenderId: '253163256490',
    projectId: 'daily-expense-tracker-b8415',
    authDomain: 'daily-expense-tracker-b8415.firebaseapp.com',
    storageBucket: 'daily-expense-tracker-b8415.firebasestorage.app',
    measurementId: 'G-GLLY3FSS2N',
  );
}
